version: "3.5"

volumes:
  postgres:
    driver: local

services:
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=limesurvey

  limesurvey:
    build: .
    ports:
      - "8080:80"
