# This workflow will prepare and test the frontend

name: LimeSurvey - Frontend - CI pipeline

# Triggers the workflow on push or pull request events on all branches
on:
  pull_request:
  push:
    branches:
      - '*'
      - '**'
      - 'dev/**'
      - 'bug/**'
      - 'feature/**'
      - 'zoho/**'

jobs:
  job_checkout_code:
    runs-on: ubuntu-18.04 # ubuntu runner hosted by Github
    name: Checkout the code
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
          
  job_build_packages:
    needs: [job_checkout_code]
    runs-on: ubuntu-18.04 # ubuntu runner hosted by Github
    strategy:
      matrix:
        # Specify what version of nodejs you want to test
        nodeJS-versions: ['10.16.3']
    name: Build Frontend Packages
    steps:
      - name: Show dir
        run: ls
        
      - name: Prepare nvm with Node ${{ matrix.nodeJS-versions }}
        run: |
          # Update
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          source ~/.nvm/nvm.sh

          # Install Node.js
          nvm install ${{ matrix.nodeJS-versions }}
          nvm use ${{ matrix.nodeJS-versions }}

      - name: Install adminbasics
        run: yarn --cwd ./assets/packages/adminbasics 
      
      - name: Build adminbasics
        run: yarn --cwd ./assets/packages/adminbasics build
    
  job_run_tests:
    needs: [job_build_packages]
    runs-on: ubuntu-18.04 # ubuntu runner hosted by Github
    name: Run Frontend Tests
    steps:
      - name: Run Tests
        run: yarn --cwd ./assets/packages/adminbasics run test
  
    
